### ISSUE TITLE
Shouldn't need to wrap parameters in double quotes

### ISSUE THREAD

**Issue by codeandcats** [Steve-Fenton/TypeSpec#13]
A user shouldn't be forced to wrap parameters in double quotes.

e.g. Instead of

Spec: `Given Dave has $400 in their account.`
Step: `(\w+) has $(\d+) in their account.`

TypeSpec requires:

Spec: `Given "Dave" has $"400" in their account.`
Step: `"(\w+)" has $"(\d+)" in their account.`

I can understand if you feel that double-quotes makes it more explicit what the parameters are, but not everyone likes that. Some people think that it looks cleaner and more natural without quotes.

Also, a spec author shouldn't necessarily concern themselves with what will become this thing called "parameters" when a developer is writing steps, and a developer should be able to target specs however they like.

For example, sometimes you might see specs like:
`Then the user should see an alert`
or
`Then the user should not see an alert`

Which could be targeted with a pattern like:
`Then the user (.+) see an alert`

But in TypeSpec the spec would need to be rewritten like:
`Then the user "should" see an alert`
or handled by writing 2 separate steps.

Given that TypeSpec is clearly targeting Gherkin, then most developers coming here will be expecting the same behaviour as other gherkin parsers and cucumber libraries which do not impose this requirement.

The above would be a minimum recommendation, though I also suggest TypeSpec stops trimming double quotes from parameters before passing them to steps as the spec writer may actually mean they expect quotes - though this would be a breaking change and require a major version bump.

**Comment by Steve-Fenton** [comment]
Okay, I have had a play with this to find the current capabilities.

All of the work to make the below test pass would be in the argument matching area. Step matching actually works out of the box.

```
Feature: Basic Working Example
    In order to remove the restriction on quoting variables
    As a BDD enthusiast
    I want to be able to use unquoted expressions

@passing
Scenario: Unquoted Expressions
    Given I am using a calculator
    And I enter an unquoted 50 into the calculator
    And I enter an unquoted 70 into the calculator
    When I press the total button
    Then the result should be an unquoted 120 on the screen
```

**Comment by Steve-Fenton** [comment]
This now works against all of the current tests and the additional unquoted expression test. We will need to watch out for any side effects for a short time just in case.
