### ISSUE TITLE
Remove duplicate TypeSpec source

### ISSUE THREAD

**Issue by codeandcats** [Steve-Fenton/TypeSpec#14]
There are 3 copies of the TypeSpec source in version control
  1. TypeSpec/Scripts/TypeSpec/TypeSpec.ts
  2. TypeSpec.Packager/content/Scripts/TypeSpec/TypeSpec.ts
  3. TypeSpec.Examples/Scripts/TypeSpec/TypeSpec.ts

I am honestly unsure as to which one is the source of truth.

Suggest moving them around so the core source is in a folder called `src` and keeping your examples separate.

I don't think there's a need to have separate directories for the npm package and nuget package, you should be able to use the same folder.

**Comment by Steve-Fenton** [comment]
The first one is the source of truth.
