### ISSUE TITLE
Remove third party libraries from version control

### ISSUE THREAD

**Issue by codeandcats** [Steve-Fenton/TypeSpec#16]
Required libraries should not be included in this project, they should instead be flagged as a dependency and pulled down from nuget and npm.

**Comment by Steve-Fenton** [comment]
Needs a path to the files in question.

**Comment by codeandcats** [comment]
3rd party files:
* TypeSpec/TypeSpec/Scripts/r.js
* TypeSpec/TypeSpec/Scripts/require.js

A better approach would be to include them as dependencies in a package.json

**Comment by Steve-Fenton** [comment]
The RequireJS NuGet package actually ships the files into the solution rather than using the "restore on build" feature... we would need to change the RequireJS package for this. I tested removing these files and they don't restore on build for other users and result in solution errors.
