### ISSUE TITLE
Upgrade Packaging Strategy

### ISSUE THREAD

**Issue by Steve-Fenton** [Steve-Fenton/TypeSpec#18]
The old packager project and batch file for NuGet and npm could be replaced by a simpler mechanism that doesn't require separate projects.

**Comment by jeskew** [comment]
Not sure if this is still on the roadmap for you, but it would be great if TypeSpec were available via NPM.

**Comment by Steve-Fenton** [comment]
It is available via NPM...

https://www.npmjs.com/package/typespec-bdd

But I accept the packaging mechanism is less than ideal and I have an issue open to sort out the Nuget and NPM packaging. I want to make it feel more natural to NPM uses, although I'm not a heavy enough user to input the knowledge.

Suggestions welcome :)

**Comment by Steve-Fenton** [comment]
Update!

The TypeSpec package on NPM, starting from v0.6.9, follows the recommended pattern for TypeScript NPM packages. It contains JavaScript files compiled with the UMD syntax, and typings files with .d.ts extensions.

https://www.npmjs.com/package/typespec-bdd

The files are all inside the "src" folder.

**Comment by Steve-Fenton** [comment]
As of version 0.7.0, TypeSpec is NPM only. This allows the packager project to be removed and encourages the charge of NPM for this kind of dependency.
