### ISSUE TITLE
Question: Will this conflict with the specflow plugin?

### ISSUE THREAD

**Issue by rhwilburn** [Steve-Fenton/TypeSpec#19]
Hi,

This project looks really awesome. Do you know if the specflow plugin in VS will create nunit etc tests for the feature files intended for typescript? Im afraid that might be quite a nuisance having it unclear which tool is used for what.

**Comment by Steve-Fenton** [comment]
Hello,

The files in the examples have a "*.txt" file extension - this is largely unimportant to TypeSpect (you can use a different extension if you like) so you can avoid file extensions supported by other tools.

The text file extension is handy for loading specifications with ajax.

I hope this helps, let me know if you have any problems.

Steve
