### ISSUE TITLE
Parsing Error When Defining Scenario After Scenario Outline

### ISSUE THREAD

**Issue by TheLandlord** [Steve-Fenton/TypeSpec#26]
Adding a scenario or scenario outline after an existing scenario outline generates a parser error.  For instance, the following feature file runs successfully when defined in this order

Feature: Launching applications
    As an electronic hobbyist
    I want to launch the serial bridge
    In order to send data to the component server

Scenario: Abort when no worker is specified
       Given the application is called without specifying a worker
       Then an error indicating a worker needs to be specified is displayed

Scenario Outline: Launch the target worker
       Given the application is called invoking the "<target>" worker
       Then the "<target>" worker runs       

Examples:
    | target    |
    | server    |
    | bridge    |
    | simulator | 

if the order of the scenario and scenario outline is changed, then parser errors are generated
Feature: Launching applications
    As an electronic hobbyist
    I want to launch the serial bridge
    In order to send data to the component server

Scenario Outline: Launch the target worker
       Given the application  is called invoking the "<target>" worker
       Then the "<target>" worker runs       
Examples:
    | target    |
    | server    |
    | bridge    |
    | simulator |

Scenario: Abort when no worker is specified
       Given the application is called without specifying a worker
       Then an error indicating a worker needs to be specified is displayed

**Parser errors generated** 
scenario: Abort when no worker is specified

Error: Did not expect line: Scenario: Abort when no worker is specified
Launching applications

       Given the application is called without specifying a worker

Error: Did not expect line: Given the applicaiton is called without specifying a worker
Launching applications

       Then an error indicating a worker needs to be specified is displayed

Error: Did not expect line: Then an error indicating a worker needs to be specified is displayed
Run has finished

**Comment by Steve-Fenton** [comment]
Thanks for reporting @TheLandlord - I have added this to the mixed specifications test case and fixed the problem. Let me know if you have any problems with the fix, which is in v2.0.0.

Please note v2.0.0 has the breaking change of using decorators, not static step registration methods. This basically makes things more natural, but leans on the experimental decorators feature.

You can enable experimental decorators in your tsconfig.json

```    "experimentalDecorators": true,```
