### ISSUE TITLE
Steps with decorators are failing to register with runner

### ISSUE THREAD

**Issue by TheLandlord** [Steve-Fenton/TypeSpec#27]
Upgraded to version 2.0, while running the calculator example, I always get the error that steps are not defined.  I have a CalculatorSteps.ts file with the proper definitions and it is getting imported as per your example.  **Can you please leave me some bread crumbs to figure out what I am doing wrong.**

Basic Working Example
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

	I am using a calculator
Basic Working Example

I am using a calculator

Error: No step definition defined.

    @step(/^I am using a calculator$/i)
    stepName(context: any) {
        throw new Error('Not implemented.');
    }
✘ Basic Working Example : Basic Example with Calculator

--------------------------------------
Basic Working Example
	In order to avoid silly mistakes
	As a math idiot
	I want to be told the sum of two numbers

	I am using a calculator
Basic Working Example

I am using a calculator

Error: No step definition defined.

    @step(/^I am using a calculator$/i)
    stepName(context: any) {
        throw new Error('Not implemented.');
    }
✘ Basic Working Example : Second example

Run has finished

**Comment by Steve-Fenton** [comment]
Hello... can I see your top level file, where you call the ```AutoRunner```?

**Comment by TheLandlord** [comment]
import readline = require("readline");
import {AutoRunner, TapReporter} from "../../node_modules/typespec-bdd/src/TypeSpec";
import {Calculator} from "../../src/Calculator";
import {CalculatorSteps} from "./steps/CalculatorSteps";

AutoRunner.testReporter = new TapReporter();

AutoRunner.run(
    "/specs/applications/features/basic.feature",
);

**Comment by Steve-Fenton** [comment]
I have one slightly odd looking change for you...

```import {CalculatorSteps} from "./steps/CalculatorSteps";```

Need to be:

```import {CalculatorSteps} from "./steps/CalculatorSteps";```

Why?!!!

The TypeScript compiler is smart enough to detect an unused import I'm your file and will optimize it away.

It isn't smart enough to realise that your steps are in fact needed!

That adjusted import statement tells the compiler not to remove it during compilation.

Let me know if you get success with that change.

**Comment by TheLandlord** [comment]
Nice!!! that did it.  I confirmed the required(....) for the CalculatorSteps is not included in the generated js file when using import {CalculatorSteps} from "./steps/CalculatorSteps", but it is generated when using import "./steps/CalculatorSteps".  I will adopt this import pattern moving forward for all steps.  Thanks for taking the time to explain why this happens.

**Comment by Steve-Fenton** [comment]
No problem. I'm adding it to the docs and adding a hint in the output for this too.
